### ISSUE TITLE
Hosted Instance - error reading config

### ISSUE THREAD

**Issue by itrickski** [lashkari/gadget-devtools#5]
hey,
we have a SaaS install on OU, but are still getting the error reading config file when attempting to add the gadget.  Do you know if OU has stopped recognizing Let's Encrypt since this was first released?

There was an error reading the configuration file. Server returned HTTP response code: 403 for URL: https://gadget.devtools.host/config.xml

**Comment by lashkari** [comment]
The error you were seeing actually had to do with Cloudflare (on the gadget's end, not OU Campus).

It should be resolved now.
